config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'contact_form/new'
  get 'contact_form/create'
  resources :add_taxis
  resources :addtaxis
  resources :contact_forms
  #get 'home/index'
  get 'home/about'
  root 'home#index'

  devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/add_taxi.rb
class AddTaxi < ApplicationRecord
end

app/models/addtaxi.rb
class Addtaxi < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/add_taxis_controller.rb
class AddTaxisController < ApplicationController
  before_action :set_add_taxi, only: %i[ show edit update destroy ]

  # GET /add_taxis or /add_taxis.json
  def index
    @add_taxis = AddTaxi.all
  end

  # GET /add_taxis/1 or /add_taxis/1.json
  def show
  end

  # GET /add_taxis/new
  def new
    @add_taxi = AddTaxi.new
  end

  # GET /add_taxis/1/edit
  def edit
  end

  # POST /add_taxis or /add_taxis.json
  def create
    @add_taxi = AddTaxi.new(add_taxi_params)

    respond_to do |format|
      if @add_taxi.save
        format.html { redirect_to @add_taxi, notice: "Add taxi was successfully created." }
        format.json { render :show, status: :created, location: @add_taxi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @add_taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_taxis/1 or /add_taxis/1.json
  def update
    respond_to do |format|
      if @add_taxi.update(add_taxi_params)
        format.html { redirect_to @add_taxi, notice: "Add taxi was successfully updated." }
        format.json { render :show, status: :ok, location: @add_taxi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @add_taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_taxis/1 or /add_taxis/1.json
  def destroy
    @add_taxi.destroy
    respond_to do |format|
      format.html { redirect_to add_taxis_url, notice: "Add taxi was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_taxi
      @add_taxi = AddTaxi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def add_taxi_params
      params.require(:add_taxi).permit(:Vehicle, :TaxiHoldername, :Registrationnumber, :Phonenumber)
    end
end

app/controllers/addtaxis_controller.rb
class AddtaxisController < ApplicationController
  before_action :set_addtaxi, only: %i[ show edit update destroy ]

  # GET /addtaxis or /addtaxis.json
  def index
    @addtaxis = Addtaxi.all
  end

  # GET /addtaxis/1 or /addtaxis/1.json
  def show
  end

  # GET /addtaxis/new
  def new
    @addtaxi = Addtaxi.new
  end

  # GET /addtaxis/1/edit
  def edit
  end

  # POST /addtaxis or /addtaxis.json
  def create
    @addtaxi = Addtaxi.new(addtaxi_params)

    respond_to do |format|
      if @addtaxi.save
        format.html { redirect_to @addtaxi, notice: "Addtaxi was successfully created." }
        format.json { render :show, status: :created, location: @addtaxi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @addtaxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addtaxis/1 or /addtaxis/1.json
  def update
    respond_to do |format|
      if @addtaxi.update(addtaxi_params)
        format.html { redirect_to @addtaxi, notice: "Addtaxi was successfully updated." }
        format.json { render :show, status: :ok, location: @addtaxi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @addtaxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addtaxis/1 or /addtaxis/1.json
  def destroy
    @addtaxi.destroy
    respond_to do |format|
      format.html { redirect_to addtaxis_url, notice: "Addtaxi was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_addtaxi
      @addtaxi = Addtaxi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def addtaxi_params
      params.require(:addtaxi).permit(:Vehicle, :Taxi, :Holdername, :Registration, :number, :Phone, :number)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_form_controller.rb
 # app/controllers/contact_forms.rb
  class ContactFormsController < ApplicationController

    def new
      @contact_form = ContactForms.new
    end

    def create
      begin
        @contact_form = ContactForms.new(params[:contact_form])
        @contact_form.request = request
        if @contact_form.deliver
          flash.now[:notice] = 'Thank you for your message!'
        else
          render :new
        end
      rescue ScriptError
        flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
      end
    end
  end

  class ContactFormsController
  module SomeConcern
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/add_taxis_helper.rb
module AddTaxisHelper
end

app/helpers/addtaxis_helper.rb
module AddtaxisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/add_taxis/_form.html.erb
<%= form_with(model: add_taxi) do |form| %>
  <% if add_taxi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(add_taxi.errors.count, "error") %> prohibited this add_taxi from being saved:</h2>

      <ul>
        <% add_taxi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field from-group">
    <%= form.label :Vehicle %>
    <%= form.text_field :Vehicle, class:"form-control" %>
  </div>

  <div class="field  from-group">
    <%= form.label :TaxiHoldername %>
    <%= form.text_field :TaxiHoldername, class:"form-control" %>
  </div>

  <div class="field from-group">
    <%= form.label :Registrationnumber %>
    <%= form.text_field :Registrationnumber, class:"form-control" %>
  </div>

  <div class="field  from-group">
    <%= form.label :Phonenumber %>
    <%= form.text_field :Phonenumber, class:"form-control" %>
  </div>

</br>
  <div class="actions">
    <%= form.submit class:"btn btn-info" %>
  </div>
<% end %>

app/views/add_taxis/edit.html.erb
<h1>Edit Taxi Details</h1>
<br/>
<%= render 'form', add_taxi: @add_taxi %>
<br/>
<%= link_to 'Show', @add_taxi, class:"btn btn-success"  %> 
<%= link_to 'Back', add_taxis_path, class:"btn btn-success" %>

app/views/add_taxis/index.html.erb
<table class="table table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Vehicle</th>
      <th>Taxiholdername</th>
      <th>Registrationnumber</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @add_taxis.each do |add_taxi| %>
      <tr>
        <td><%= add_taxi.Vehicle %></td>
        <td><%= add_taxi.TaxiHoldername %></td>
        <td><%= add_taxi.Registrationnumber %></td>
        <td><%= add_taxi.Phonenumber %></td>
        <td><%= link_to 'Show', add_taxi %></td>
        <td><%= link_to 'Edit', edit_add_taxi_path(add_taxi) %></td>
        <td><%= button_to 'Destroy', add_taxi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Taxi', new_add_taxi_path, class:"btn btn-success" %>

app/views/add_taxis/new.html.erb
<h1> Add New Taxi</h1>

<%= render 'form', add_taxi: @add_taxi %>
</br>
<%= link_to 'Back', add_taxis_path, class:"btn btn-primary" %>

app/views/add_taxis/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @add_taxi.Vehicle %></h1>
  <p> <strong>Taxiholdername:</strong> <%= @add_taxi.TaxiHoldername %></p>
  <p> <strong>Registrationnumber:</strong><%= @add_taxi.Registrationnumber %></p>
   <p> <strong>Phonenumber:</strong><%= @add_taxi.Phonenumber %></p>
  <%= link_to 'Edit', edit_add_taxi_path(@add_taxi), class:"btn btn-success" %> 
  <%= link_to 'Back', add_taxis_path,  class:"btn btn-success"  %>
</div>

app/views/addtaxis/_form.html.erb
<%= form_with(model: addtaxi) do |form| %>
  <% if addtaxi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(addtaxi.errors.count, "error") %> prohibited this addtaxi from being saved:</h2>

      <ul>
        <% addtaxi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Vehicle %>
    <%= form.text_field :Vehicle %>
  </div>

  <div class="field">
    <%= form.label :Taxi %>
    <%= form.text_field :Taxi %>
  </div>

  <div class="field">
    <%= form.label :Holdername %>
    <%= form.text_field :Holdername %>
  </div>

  <div class="field">
    <%= form.label :Registration %>
    <%= form.text_field :Registration %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :Phone %>
    <%= form.text_field :Phone %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addtaxis/edit.html.erb
<h1>Editing Addtaxi</h1>

<%= render 'form', addtaxi: @addtaxi %>

<%= link_to 'Show', @addtaxi %> |
<%= link_to 'Back', addtaxis_path %>

app/views/addtaxis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addtaxis</h1>

<table>
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Taxi</th>
      <th>Holdername</th>
      <th>Registration</th>
      <th>Number</th>
      <th>Phone</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addtaxis.each do |addtaxi| %>
      <tr>
        <td><%= addtaxi.Vehicle %></td>
        <td><%= addtaxi.Taxi %></td>
        <td><%= addtaxi.Holdername %></td>
        <td><%= addtaxi.Registration %></td>
        <td><%= addtaxi.number %></td>
        <td><%= addtaxi.Phone %></td>
        <td><%= addtaxi.number %></td>
        <td><%= link_to 'Show', addtaxi %></td>
        <td><%= link_to 'Edit', edit_addtaxi_path(addtaxi) %></td>
        <td><%= link_to 'Destroy', addtaxi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Taxi', new_addtaxi_path %>

app/views/addtaxis/new.html.erb
<h1>New Addtaxi</h1>

<%= render 'form', addtaxi: @addtaxi %>

<%= link_to 'Back', addtaxis_path %>

app/views/addtaxis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle:</strong>
  <%= @addtaxi.Vehicle %>
</p>

<p>
  <strong>Taxi:</strong>
  <%= @addtaxi.Taxi %>
</p>

<p>
  <strong>Holdername:</strong>
  <%= @addtaxi.Holdername %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @addtaxi.Registration %>
</p>

<p>
  <strong>Number:</strong>
  <%= @addtaxi.number %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @addtaxi.Phone %>
</p>

<p>
  <strong>Number:</strong>
  <%= @addtaxi.number %>
</p>

<%= link_to 'Edit', edit_addtaxi_path(@addtaxi) %> |
<%= link_to 'Back', addtaxis_path %>

app/views/contact_form/create.html.erb
<h1>ContactForm#create</h1>
<p>Find me in app/views/contact_form/create.html.erb</p>

app/views/contact_form/create.html.haml
  %h1 Thank you for your message.

  %p
    We'll get back to you as soon as possible.

  %p
    = link_to 'Home', root_url, :class => 'button'

app/views/contact_form/new.html.erb
<h1>ContactForm#new</h1>
<p>Find me in app/views/contact_form/new.html.erb</p>

app/views/contact_form/new.html.haml
  = simple_form_for @contact_form do |f|
    = f.input :name, :required => false
    = f.input :email, :required => false
    = f.input :message, :as => :text, :required => false
    .hidden
      = f.input :nickname, :hint => 'Leave this field blank!'
    = f.button :submit, 'Send message'

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Edathinakathupady', root_path, class:"navbar-brand" %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
        	<%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
         <li class="nav-item">
        	<%= link_to 'Taxi', add_taxis_path, class:"nav-link" %>
        </li>

          <li class="nav-item">
          <%= link_to 'Contact', contact_form_create_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'Add Taxi', new_add_taxi_path, class:"nav-link" %>
                  </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us....</h1>
<p> <h3> This is a demo website containing information on the place, shops, taxis, and buses through Edathinakathupady</h3> </p>

app/views/home/index.html.erb
<h1>Hello World!!!!</h1>
<p><h3>This website shows details about a place called Edathinakathupady, Kottayam, Kerala.

It display the information about the place briefly, taxis available, shops etc. in that location</h3></p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 	<%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>List</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">

    </br>

    <% if notice %>
      <%= render "layouts/alerts" %>
    <% end %>
      <%= yield %>
    </div>
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>